### ISSUE TITLE
CMakeLists.txt incorrectly sets the samples directory for >= 11.6

### ISSUE THREAD

**Issue by trevor-vincent** [Dr-Noob/gpufetch#15]
Hi, thank you for making this awesome tool!

gpufetch would not compile on my computer because the samples directory no longer exists in v11.6, it has moved to here:

https://github.com/NVIDIA/cuda-samples

So you need to fix the CMakeLists.txt to this:

```
  # https://docs.nvidia.com/cuda/cuda-samples/index.html#new-features-in-cuda-toolkit-11-6
  # Not sure about this. Why the heck did they change this?
  if(${CMAKE_CUDA_COMPILER_VERSION} VERSION_GREATER_EQUAL "11.6")
    include(FetchContent)
    FetchContent_Declare(
      cudasamples
      GIT_REPOSITORY https://github.com/NVIDIA/cuda-samples
    )
    FetchContent_MakeAvailable(cudasamples)
    set(CUDA_SAMPLES_PATH ${cudasamples_SOURCE_DIR}/Common)
  else()
    set(CUDA_SAMPLES_PATH ${CMAKE_CUDA_COMPILER_TOOLKIT_ROOT}/samples/common/inc)
  endif()
```

After this change it compiles fine.

**Comment by Dr-Noob** [comment]
Hey, this idea looks good, but it would require a newer version of CMake, which is something I would prefer to avoid. But I guess it could be done using `ExternalProject_Add`, which is already used in the CMake.

Anyhow, I decided to remove the `cuda-samples` dependency for the project because sometimes it's a pain in the ass to find it, and the program only needs a dummy function that can be easily inlined. So this will not be an issue anymore. Anyway, thanks for the idea!
