### ISSUE TITLE
[ERROR]: Unkown Intel device id: 0x9A49

### ISSUE THREAD

**Issue by Lqnz** [Dr-Noob/gpufetch#5]
Hi!
So basically I built gpufetch in source and once I did **./gpufetch**; It immediately got an error which is this: https://i.imgur.com/vGWW55q.png

Even though I set my NVIDIA graphics card as my main GPU, not my integrated graphics card.

**Comment by Dr-Noob** [comment]
I released the support for Intel iGPU recently so it's expected to find bugs easily :sweat_smile: 

I fixed the segfault. Now, if you run the program again, the output will be the same but without the segfault. At the moment, gpufetch does not support your Intel iGPU (it's too new, I will add support soon), so that's why you see that error.

Now, the question is: Are you sure that you have your NVIDIA card enabled? You can check easily with `lspci -nn | grep VGA`.

**Comment by Lqnz** [comment]
> I released the support for Intel iGPU recently so it's expected to find bugs easily sweat_smile
> 
> I fixed the segfault. Now, if you run the program again, the output will be the same but without the segfault. At the moment, gpufetch does not support your Intel iGPU (it's too new, I will add support soon), so that's why you see that error.
> 
> Now, the question is: Are you sure that you have your NVIDIA card enabled? You can check easily with `lspci -nn | grep VGA`.

Sorry for the late reply but I typed the command and it says that I am using the integrated graphics card (bruh) but I swear I switched my main graphics card to NVIDIA

**Comment by Dr-Noob** [comment]
If NVIDIA GPU is disabled then it has nothing to do with gpufetch.

However, now that you have your Intel iGPU enabled, you can try if gpufetch works with it...When you posted the issue, your iGPU was not supported, but now, with the latest commits, it work. And if you can switch to the NVIDIA GPU afterwards, you can try it too.

**Comment by Lqnz** [comment]
Alright nice man. Thank you very much!
