### ISSUE TITLE
Wrong RAM size detect.

### ISSUE THREAD

**Issue by Csokis** [Dr-Noob/gpufetch#8]
Hi!

I have an **MSI GeForce GTX 1650 Super** card with 4GB RAM. However, the program only says 3GB, which is wrong.

[Gpufetch](https://i.imgur.com/EX9mYrm.png)

[nvidia-smi](https://i.imgur.com/5AkeGqA.png)

The program is the latest git version (gpufetch v0.21).

**Comment by Dr-Noob** [comment]
Yeah, this was something I was worried about. 

I have fixed it in the latest commit by showing the memory size in MiB, so it should work now.

**Comment by Csokis** [comment]
It works, but couldn't it be rounded? 3904 MiB GDDR6 to 4 GiB GDDR6. Or is it not that simple? :thinking:

**Comment by Dr-Noob** [comment]
Well, for me is not so clear that rounding 3904 MiB to 4 GiB is better since you are losing information since 3904 MiB != 4 GiB. CUDA reports some less than 4 GiB. It seems that the remaining memory is used for the driver and stuff like that. 

After thinking about this, I think that `gpufetch` should print the GPU memory of the device (4096 MiB), and not necessarily the real memory (3904 MiB). So I've updated the project with this change.

Last but not least, I saw that `gpufetch` says that your GPU has tensor cores, but I saw that this is incorrect (you can check [this anandtech report](https://www.anandtech.com/show/13973/nvidia-gtx-1660-ti-review-feat-evga-xc-gaming/2) for more information). So I also committed a patch for this.

Can you try the latest version and check that outputs `4 GiB GDDR6` and no tensor cores? Thanks!

**Comment by Csokis** [comment]
It already shows 4GiB, but unfortunately also Tensor cores!

[https://i.imgur.com/HTHEfml.png](https://i.imgur.com/HTHEfml.png)

Thank You! :+1:

**Comment by Dr-Noob** [comment]
That was a dummy mistake on my part :sweat_smile:. I just updated it, can you try again and report back?

**Comment by Csokis** [comment]
Sure! :smile:

[https://i.imgur.com/eQZzwig.png](https://i.imgur.com/eQZzwig.png)

Now that's OK!  :+1:  But where did the nvidia text go?!

**Comment by Dr-Noob** [comment]
Yeah, maybe this should be better documented. 

The program displays two different logos, depending on the size of the terminal. If the terminal is long enough, it will display this logo (second screenshot). If the terminal is smaller, the output would not fit in one line, so it displays a smaller logo (first screenshot). This is completely normal 😉

**Comment by Dr-Noob** [comment]
Soon I'll add an option to choose between the two logos manually, overriding the default selection based on the terminal size (see #11)

**Comment by Dr-Noob** [comment]
> Sure! smile
> 
> https://i.imgur.com/eQZzwig.png
> 
> Now that's OK! +1 But where did the nvidia text/label go?!

Now you can manually print the logo with the NVIDIA text if you want with `--logo-short`
